### ISSUE TITLE
Localization Issues

### ISSUE THREAD

**Issue by Vyraal1** [Martacus/Solar#1]
Menhir doesn't seem to be localized:
![image](https://user-images.githubusercontent.com/26587049/37050806-cde2a2aa-2142-11e8-9f9e-d4edbcfe88fd.png)

Ritual Stones don't seem to be localized:
![image](https://user-images.githubusercontent.com/26587049/37050843-e7b3f3f0-2142-11e8-9aaf-d213e37bcbf1.png)

Same with Sundials:
![image](https://user-images.githubusercontent.com/26587049/37050849-eecc78ec-2142-11e8-9b3c-e24727e59db9.png)

**Comment by Martacus** [comment]
Ritual stone is like that for a purpose but the other 2 were string replacement issues. Thanks for noticing :). Fixed in the next hotfix
