### ISSUE TITLE
Gun powder doesn't work in Rune Infuser

### ISSUE THREAD

**Issue by DWX12** [Martacus/Solar#11]
Gun powder just sits in rune infuser and does nothing.

And when right clicking to reclaim items with amulet, they are deleted. Not sure if that's intentional or not, but you can still shift right click with an empty hand to reclaim the rune.

**Comment by Martacus** [comment]
Gun Powder is a reagent for fire runes. But it is not the active one. And yes that works as intended. Runes can be retrieved but items cant.
