### ISSUE TITLE
[Suggestion] UI Changes

### ISSUE THREAD

**Issue by Vyraal1** [Martacus/Solar#2]
![image](https://user-images.githubusercontent.com/26587049/37050580-3b6e9906-2142-11e8-9285-9c4fabd12bbb.png)
When hovering over the journal icon, or the Ritual Icon in the book, would it be possible to have a text tooltip that appears (either in the bottom middle of the screen or near to the mouse, etc.) that says what I'm hovering over? For these two it's pretty simplistic, but it adds more intuition for future tabs that I'm looking over the "Rituals" section or "Table of Contents".

![image](https://user-images.githubusercontent.com/26587049/37050668-76a33c02-2142-11e8-854f-396201036cf9.png)
Similar suggestion for when reviewing the Ritual Drawings, when hovering over a rune it might be better it have a tooltip stating what rune I'm hovering over.

**Comment by Martacus** [comment]
Thanks for the suggestion. Definitely something I'm adding!

**Comment by Martacus** [comment]
Added!
