### ISSUE TITLE
[Suggestion] Ritual Activations/Feedback

### ISSUE THREAD

**Issue by Vyraal1** [Martacus/Solar#5]
1) Would it be possible to add some particle effects or even a basic text output that a ritual is  successfully activated? It can range from having custom particles to each rune (eg, whenever a sun rune gets used, its vaporized in a flash of light, or a fire rune burns away when the ritual starts) to something simple as the runes simply disappearing but there will be a text output stating "Ritual Activated!".

Some ritual effects like Ritual of Clear Skies/Rain obviously don't need this as the effect can be immediate, however for some of the other rituals like Rite of High Tides, it used up my ingredients, and it was hard to see if the pond was growing or not. I tried moving the ritual to directly above the pond water source blocks, and it was hard to observe as well.

2) Inverse to the first issue is having some feedback to the player that ritual wasn't successful such as failing to use any ingredients at all, or text output that says "Components are missing", etc.

3) Is there a duration on the Ritual of Rain? It's actually been 12 ingame minecraft days after I activated it, and it actually still seems to be raining.

Overall I'm not really asking for exact details and a GUI of how much energy I need for XYZ operation, that's too much and seems like it would the thematically inconsistent, but I would prefer mechanics (sounds, particle effects, text, etc.) that give me feedback if I'm moving in the right/wrong direction so I can adjust accordingly.

**Comment by Martacus** [comment]
Yes very much so, that's 100% on the agenda. Also the ritual of the High Tides specifies its a spell. Use your amulet on the pond.

As for the rain. I just set raining to true I would have expected it to automatically switch the weather back but I guess not lol

**Comment by Martacus** [comment]
Ive added some feedback and more is coming. Closing this
