### ISSUE TITLE
Server Crash again

### ISSUE THREAD

**Issue by knoxhack** [Martacus/Solar#8]
https://gist.github.com/knoxhack/4cdb4bf750badafcba2dfdb7c95de3b4

**Comment by knoxhack** [comment]
using version Solar-0.0.2.11

**Comment by Martacus** [comment]
Working on fixing them, I am getting the most weird errors. Please stand by :P

**Comment by knoxhack** [comment]
👍

**Comment by Martacus** [comment]
New build is pending on curseforge :)
